### PR TITLE
changing behavior of "split" flag for AE events

### PR DESCRIPTION
**Pull request by ghoshsuman**
Modified code to produce to event output at individual left-right channels, and stereo channel simultaneously, for AE events.
"--split true" produces output at all 3 channels: /vPreProcess/AE:o, /vPreProcess/left:o, /vPreProcess/right:o
"--split false" produces output only at /vPreProcess/AE:o channel

Behavior for APS output left unchanged

### CODE REVIEW

**Comment by arrenglover** [comment]
Looks good @ghoshsuman there is no problems, but just some functionality I would like. I think the best (to try to save computation as much as possible) is to have 2 flags `--split_stereo` and `--combined_stereo`. If `--split_stereo` is true you output on `left/AE:o` and `right/AE:o`, (we'll need to change these port names) if `--combined_stereo` is true you output on `/AE:o`. If both are true you output on all ports. If `--split_stereo` is false then `--combined_stereo` should default to true and output on `/AE:o` anyway.

Does it make sense?

**Comment by ghoshsuman** [comment]
Okay. I'll make the changes. When both flags are forced to be false, should I output on /AE:o anyway?

**Comment by arrenglover** [comment]
> When both flags are forced to be false, should I output on /AE:o anyway?

> If --split_stereo is false then --combined_stereo should default to true and output on /AE:o anyway.

yes

**Comment by ghoshsuman** [comment]
Added the functionality you asked, for both AE and APS outputs. Please check.

**Pull request merged**
