### PR TITLE
added hexviewer v0.1

### PR DESCRIPTION
**Pull request by arrenglover**
@mcasti-iit - please checkout this branch and compile (make install) event-driven (no sudo). the new ``vHexviewer`` should be available. It will open a port /vHexviewer/AE:i which you need to connect to /zynqGrabber/AE:o with fast_tcp. use ``--mask 0x01`` for example as a mask so that only events with the LSB == 1 is shown.

the printed "==" mean it is a packet break. I can customise the output as you like (i.e. if you want to expert the data to a file etc.)

Give me a call if you have problems. If there are no issues, we can discuss this merge.

### CODE REVIEW

**Comment by arrenglover** [comment]
@mcasti-iit feeback:
3 states: 0, 1, x (don't care)
give mask in binary (not hex)
anything else?

is it okay to separate the packets by the line? or do you prefer to stack all the events together without packet separation?

**Comment by mcasti-iit** [comment]
Thank you very much, Arren; for the moment the App is all I need. 
Packet separation is good.

**Comment by arrenglover** [comment]
@mcasti-iit  I have added the options you like use `--mask 100x01x01` to define which bits you care about and what they should be. note: any value other than `0` or `1` is treated as 'don't care'

please check it works and then approve the pull request to merge it into master.

**Comment by mcasti-iit** [comment]
Thank you Arren; current version of  vHexviewer is just what I needed!

**Pull request merged**
