### PR TITLE
atis gen3 bridge to YARP using the Metavision SDK

### PR DESCRIPTION
**Pull request by arrenglover**
a single module that will connect to a Gen3 USB camera and stream the address events over YARP. This uses the SDK and requires the Metavision SDK installed. Install using the cmake ENABLE_atis3 flag with HARDWARE_IO=ON. Optionally use the `--file <path>` to load a dataset instead of a camera.

It has been tested using only datasets from metavision, and will need testing with a real camera before merging. 

As it uses the SDK there are 2 options to improve speed/throughput if it is a problem.
slightly faster: use the raw data from the SDK to reduce 1 layer of decoding. requires knowledge of the data coding.
much faster: use the Metavision HAL instead of the SDK to directly read buffers from the camera. requires knowledge of all data streamed from the camera (e.g. meta-events)

if the current solution is not viable for real-time we can consider these other 2 immediately.

@Iaxama @GiuliaDAngelo @aikolina - anyone that has time to test this with a real camera would be useful.

### CODE REVIEW

**Comment by Iaxama** [comment]
After testing with a real camera plugged in the data seems to be going through fine. However, the visualization lags. Requires further investigation to check the source of lag. I will look into it.

**Comment by arrenglover** [comment]
@Iaxama @GiuliaDAngelo I've pushed a changed that should improve things. I think it will work "well" sending the data to the vPreProcess and using the filters before sending through the vFramer. Sending directly to vFramer might be slow, so I think at that point it is a problem with vFramer rather than this module. Please let me know how it goes with the real camera.

**Comment by Iaxama** [comment]
@arrenglover I have tested the latest changes with the camera and I still get a laggy response. I do see some improvements, but still far from real time or even usable. Of course at the moment my analysis is purely qualitative. Maybe we can try play a bit with the parameters of the filters in the vPreProcess because I still see a lot of noise events even when the camera lens is completely covered. I attach the application xml file used during testing. 

[eyesviewer-localhost-atisgen3.zip](https://github.com/robotology/event-driven/files/5837277/eyesviewer-localhost-atisgen3.zip)

**Comment by arrenglover** [comment]
okay - you can double check the filters are actually on at this point too by setting `--filter_spatial true` and `--filter_temporal true` as `vPreProcess` parameters.

the biggest cause of delay in the visualisation can be the size of the packet that gets sent. lots of small packets have overhead but you can visualise the data evolving over time, one large packet has the greatest throughput - but will only have 1 frame visualised and looks terrible.

With our current system there is a *maximum packet size* that makes sure data is sent over the port often. maybe this is a solution here too, but has other ramifications to do so.

to understand where the delay is coming now we can look at 2 things.
1. the output of the `atis-bridge-sdk` shows the number of packets sent per second and the event rate for that second. Easiest thing to look for is that the number of packets sent is > 1, and hopefully around 1000 (1 packet per ms)
2. the output of `vPreProcess` should also say if it has many packets *in delay*. hopefully it stays around 0 but depending on the situations some tens of packets should be fine.

If both these modules are doing as expected then we know it's just in the vFramerLite, which is the best scenario for us at the moment.

Let me know

**Comment by Iaxama** [comment]
@arrenglover I have double checked the filters were active by adding the parameters (but i think they were already active by default). The vPreProcess however does not output anything besides port connections. Do I need to add any verbose parameter??

The atis-bridge instead shows logs like the following:
```[INFO] 913 packets and 39.723 k events sent per second
[INFO] 918 packets and 39.989 k events sent per second
[INFO] 913 packets and 38.243 k events sent per second
[INFO] 921 packets and 38.773 k events sent per second
[INFO] 923 packets and 38.637 k events sent per second
[INFO] 919 packets and 39.21 k events sent per second
[INFO] 912 packets and 38.975 k events sent per second
[INFO] 913 packets and 39.02 k events sent per second
[INFO] 920 packets and 38.801 k events sent per second
[INFO] 923 packets and 39.806 k events sent per second
[INFO] 909 packets and 38.45 k events sent per second
[INFO] 917 packets and 74.72 k events sent per second
[INFO] 917 packets and 249.406 k events sent per second
[INFO] 918 packets and 76.915 k events sent per second
[INFO] 929 packets and 158.885 k events sent per second
[INFO] 933 packets and 936.666 k events sent per second
[INFO] 946 packets and 1196.46 k events sent per second
[INFO] 935 packets and 1126.18 k events sent per second
[INFO] 931 packets and 1254.32 k events sent per second
[INFO] 941 packets and 1203.99 k events sent per second
[INFO] 944 packets and 1275.72 k events sent per second 
```
I think it is interesting to notice that the amount of packets being sent stays more ore less unchanged even when the number of events per seconds increases significantly. I don't know how the packets are being filled though, so I am not sure if it's a useful analysis.

**Comment by arrenglover** [comment]
Are you sure ports were connected (and not broken in some hidden way). `vPreProcess` should print things as long as some events arrive. also if no events are being sent from `atis-bridge-sdk` it should work well (i.e. 1000 packets / second).

1000 K events isn't too many. Did you move the camera quickly? it seems like we should easily operate well at 1000 K events so I can't draw conclusions from this file. I think we will experience problems at 10,000 or 20,000 K events per second.

**Review by Iaxama — APPROVED** [review]

**Pull request merged**
