### PR TITLE
program ATIS bias with current (using header information in bias values)

### PR DESCRIPTION
**Pull request by arrenglover**
…vs voltage) based on a bit in the header of each bias.

### CODE REVIEW

**Comment by arrenglover** [comment]
The premise of this pull request is to change the bias programming to automatically assume current biasing if the header of the bias file indicates it should be. @simbamford says it should be current if the header has a 1 in the LSB. However, in both my bias files, for current and for voltage, they always have a 1 in the LSB. Can you clear this up Sim?

**Comment by simbamford** [comment]
> The premise of this pull request is to change the bias programming to automatically assume current biasing if the header of the bias file indicates it should be. 

That's the status before the PR - the PR changes the code to allow per-bias decision about how to interpret the bias. Note that the "header" value comes from unpacking the control code on each row of the bias file. 

>@simbamford says it should be current if the header has a 1 in the LSB. However, in both my bias files, for current and for voltage, they always have a 1 in the LSB. Can you clear this up Sim?

0=current, 1=voltage. The bias files we have are written using exclusively voltage biasing.

**Comment by arrenglover** [comment]
Good. We both saying the same thing for the purpose of the PR, i must not have been clear as you have misinterpreted it.

In event-driven there are bias files for both voltage and current, I compared them looking at the header for each bias. in both files the header values are odd. Check here for a current bias file:
https://github.com/robotology/event-driven/blob/master/src/hardwareio/zynqGrabber/bias_files/chris_WS_current.ini

**Comment by simbamford** [comment]
> 
> 
> Good. We both saying the same thing for the purpose of the PR, i must not have been clear as you have misinterpreted it.
> 
> In event-driven there are bias files for both voltage and current, I compared them looking at the header for each bias. in both files the header values are odd. Check here for a current bias file:
> https://github.com/robotology/event-driven/blob/master/src/hardwareio/zynqGrabber/bias_files/chris_WS_current.ini

Indeed that file doesn't agree with this PR. Did that file come directly from Chronocam without modification?

**Comment by arrenglover** [comment]
The values came directly from Chris Posch. I don't think we would have changed them.

**Comment by simbamford** [comment]
Then I think we should put this on hold until we once again put attention to ATIS programming.

**Pull request closed without merging**
