### PR TITLE
ubuntu-20.04 compatibility (OpenCV4)

### PR DESCRIPTION
**Pull request by arrenglover**

### CODE REVIEW

**Comment by arrenglover** [comment]
@ddetommaso I think I've fixed all compatibility issues. If you're still using event-driven, do you mind checking it still compiles on your machine?

**Comment by ddetommaso** [comment]
> 
> 
> @ddetommaso I think I've fixed all compatibility issues. If you're still using event-driven, do you mind checking it still compiles on your machine?

Hi @arrenglover 

great work! I would need some days to be able to check this, but I can definitively do it!

**Comment by ddetommaso** [comment]
I confirm that everything compiles perfectly!

**Comment by arrenglover** [comment]
> I confirm that everything compiles perfectly!

thanks very much!

**Pull request merged**
