### PR TITLE
atis-bridge-sdk for phrophesee v1.4

### PR DESCRIPTION
**Pull request by arrenglover**
updated the atis-bridge-sdk to work for both version of metavision/prophesee libraries we are using. only one application exists which builds correctly for whichever libraries are found using the CMAKE flags. tested in both dockers for gen3:latest and gen3:v1.4

### CODE REVIEW

**Comment by arrenglover** [comment]
@Iaxama

**Comment by Iaxama** [comment]
When compiling the prophesee_core i am getting an error related to the boost version (See error below). Which version do you have??

Running on eventdrivenrobotics/event-driven:bionic_yarp_v3.3.2_ed_v1.5

CMake Error at /usr/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:218 (message):
  Could NOT find Boost (missing: system filesystem) (found version "1.65.1")
Call Stack (most recent call first):
  /usr/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:582 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.19/Modules/FindBoost.cmake:2208 (find_package_handle_standard_args)
  /usr/lib/prophesee_core/prophesee_core-config.cmake:41 (find_package)
  CMakeLists.txt:66 (find_package)


-- Configuring incomplete, errors occurred!
See also "/usr/local/src/event-driven/build/CMakeFiles/CMakeOutput.log".

**Comment by arrenglover** [comment]
you already have an issue assigned to you on your repository about it:

https://github.com/event-driven-robotics/atis-gen3-docker/issues/1

**Comment by Iaxama** [comment]
https://github.com/event-driven-robotics/atis-gen3-docker/issues/1 This has been fixed, so if you could try to run the bridge with the camera on the latest atis3 docker as a final test we can merge the PR @arrenglover

**Comment by arrenglover** [comment]
@Iaxama I think it's unnecesary - I already tested that event-driven compiles with both sets of libraries as I said when I opened the issue. If the dockers aren't working it is a different issue. If you don't see anything suspicious in the code https://github.com/robotology/event-driven/pull/131/files then please approve the PR

**Review by Iaxama — APPROVED** [review]

**Pull request merged**
