### PR TITLE
Python dev

### PR DESCRIPTION
**Pull request by simbamford**
under python: 
libraries/bimvee 
visualizer (ntupleviz)

### CODE REVIEW

**Comment by arrenglover** [comment]
there is one image in the pull request. What is it for?

**Comment by simbamford** [comment]
> 
> 
> there is one image in the pull request. What is it for?

This is an image that the visualiser uses to tell the user that data is missing.

**Comment by arrenglover** [comment]
@Iaxama - we still need your input to make sure this isn't going to change anything you need in the repo as it is currently. Does it all smoothly integrate so you won't be affected?

**Comment by arrenglover** [comment]
@Iaxama @simbamford - what's the status on this pull request?

**Comment by arrenglover** [comment]
@Iaxama - waiting on you to approve. Your last comment is to request changes.

**Pull request merged**
