### PR TITLE
Cleaned up script for collapsing bottle of events

### PR DESCRIPTION
**Pull request by Iaxama**
Cleaned up python script for event collapse

### CODE REVIEW

**Comment by arrenglover** [comment]
there seems to be many __init__.py files that aren't related to this pull request. can we remove them and put them in the request when you merge the reader / visualisation?

**Comment by Iaxama** [comment]
Sorry that was indeed not part of the PR. If you could only merge the first commit that would be great

**Comment by arrenglover** [comment]
as far as I can tell - changes to the pull request need to be done locally and pushed, so maybe google how to remove that commit from the branch that is already pushed to remote.

**Comment by Iaxama** [comment]
Hi I have moved the development stuff for python in the python_dev branch. This PR is only related to the event_collapse script. I have also changed the script so that it can accept any type of event (AE, IMU...). Do we need to consider the case where we have in the same file multiple event types?

**Comment by arrenglover** [comment]
> Do we need to consider the case where we have in the same file multiple event types?

no

**Comment by simbamford** [comment]
I changed my mind about this - importing and re-exporting might be more prinicipled but it's inefficient because it unecessarily decodes and recodes the events, whereas this just reorders them - so this should remain. In any case, it seems well written.

**Pull request merged**
