### PR TITLE
master update (minor revision)

### PR DESCRIPTION
**Pull request by arrenglover**

### CODE REVIEW

**Comment by arrenglover** [comment]
Ciao @Iaxama ,

Can you please have a look at this quickly, I've already checked it and it seems fine. Then just have to press the approve button. I'll do the merge itself. Thanks

**Comment by Iaxama** [comment]
Hi I have tested compilation, install and uninstall for all modules and I could compile almost everything. I could not test the chronocamgrabber because i don't have the driver and reptest and vergence applications could not compile with some linking error. I have disabled them and not investigated further. Are we going to maintain those modules?

**Comment by arrenglover** [comment]
Thanks @Iaxama ! 

I can compile and install reptest and vergence without any problems. Maybe you need BUILD_DEPRECATED ON?

Chronocamgrabber I need the same driver, I have it but last time I tried I couldn't get it to install well. I'll merge in these changes to master in any case and we can see if we want to maintain chronocamgrabber later

**Comment by arrenglover** [comment]
@Iaxama please also read what I have written above.

> I'll do the merge itself.

I wasn't sure exactly which way I wanted to complete the merge, and wanted to merge it myself.

**Pull request merged**
