### PR TITLE
Python dev

### PR DESCRIPTION
**Pull request by Iaxama**
Bug fixes and improvements for both bimvee libraries and visualizer.
- Added support for Celex camera
- Improved flexibility for rosbag loading from GUI

### CODE REVIEW

**Comment by arrenglover** [comment]
@simbamford - @Iaxama mentioned that this merge becomes messy as python_dev has already been merged before. Now github is trying to go back to the complete ancestor of python_dev branch (master before the last merge)  to do the comparison, rather than just doing the changes between the current version of master and any new changes to python_dev.

**Comment by arrenglover** [comment]
@Iaxama or @simbamford  - the best thing would be to do the diff comparison on your local machine so you get just the new changes. I would like to do it as a squashed commit so compile a list of relevant updates to include in the commit notes. Then I'll do the commit once you both say there is no problems.

**Comment by arrenglover** [comment]
@Iaxama - but first the branch has conflicts that need to be resolved. You'll need to merge devel into python_dev and fix any conflicts. Then push python_dev again.

**Comment by Iaxama** [comment]
I have fixed the conflicts by accepting the latest changes in python dev. It should be much easier to merge now

**Pull request merged**
