### PR TITLE
Sec visualiser

### PR DESCRIPTION
**Pull request by simbamford**
visualiser examples file and importsecdvs brought to standard of treating folders as modules; examples include secdvs import; other improvements to the examples file.

### CODE REVIEW

**Comment by arrenglover** [comment]
@simbamford - I added @AArriandiaga as the reviewer of this PR as you suggested.

**Comment by arrenglover** [comment]
ping @AArriandiaga - Sim wanted you to do this code review. Can you help out? Do you know what to do?

**Comment by AArriandiaga** [comment]
> ping @AArriandiaga - Sim wanted you to do this code review. Can you help out? Do you know what to do?

Yes, I'll do. However, I don't know how the "Review" works. I'll check and run the code, and if I find something that is not working I'll try to fix it.

**Comment by arrenglover** [comment]
@AArriandiaga you should check through the [changes](https://github.com/robotology/event-driven/pull/94/files) and by eye double check you can't see a glaring mistake, or a design decision that you think needs more thought. Making sure the code runs is nice as well (in theory we should make that part automated though like for C++). 

Sim chose you as the code is something relevant to what you are doing.

**Comment by AArriandiaga** [comment]
@arrenglover Ok, thanks

**Comment by arrenglover** [comment]
@AArriandiaga do you have time to complete this review (it shouldn't take long right?). we want to get these pull requests completed within a couple of days.

**Pull request merged**
